server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://127.0.0.1:5432/traffic_policing?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379

logging:
  level:
    com.gyh.gis.mapper: DEBUG
    com.gyh.gis.support.shardingtable.metadata: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    groups:
      enabled: true
  show-actuator: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

gis:
  storage-metadata:
    configs:
      device10minute_history:
        sharding-table-max-rows: 1_000_000
        originTableName: device_10minute_history
        createShardingTableSQLFile: classpath:/device_10minute_history.sql
        policyType: NEVER
      device_day_history:
        sharding-table-max-rows: 1_000_000
        originTableName: device_day_history
        createShardingTableSQLFile: classpath:/device_day_history.sql
        policyType: NEVER
      test:
        sharding-table-max-rows: 1
        originTableName: test
        createShardingTableSQLFile: classpath:/test.sql
        policyType: NEVER